# Generated by Django 4.1.1 on 2022-10-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company_location_alter_company_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='position_in_company',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
