# Generated by Django 4.1.1 on 2022-10-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_company_position_in_company_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='company',
            name='staff_strength',
            field=models.CharField(blank=True, max_length=50, verbose_name='Number of employees'),
        ),
    ]
