# Generated by Django 4.1.1 on 2022-10-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_company_company_email_company_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
