# Generated by Django 4.1.1 on 2022-10-08 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_company_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('cv', models.FileField(blank=True, upload_to='cvs', verbose_name='Upload CV')),
                ('image', models.ImageField(blank=True, upload_to='employees')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('supervisor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('task_description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='account.employee')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('PS', 'Primary School'), ('SS', 'Secondary School'), ('VO', 'Vocational School'), ('CE', 'College of Education'), ('PO', 'Polytechnic'), ('UI', 'University')], max_length=2)),
                ('name_of_institution', models.CharField(max_length=50)),
                ('year_of_graudation', models.PositiveIntegerField()),
                ('course_of_study', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='account.employee')),
            ],
        ),
    ]
