# Generated by Django 4.0.2 on 2022-03-03 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_alter_category_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply',
            new_name='Application',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, upload_to='applicants'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
