# Generated by Django 4.1.1 on 2022-10-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_category_alter_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary_amount',
            new_name='base_salary_amount',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='job',
            name='maximum_salary_amount',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='qualification_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Qualification title'),
        ),
    ]
