# Generated by Django 4.1.1 on 2022-10-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_salary_amount_job_base_salary_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='maximum_salary_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
