# Generated by Django 4.0.2 on 2022-03-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_apply_application_alter_applicant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobs.category'),
            preserve_default=False,
        ),
    ]
