# Generated by Django 4.0.2 on 2022-03-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applicant_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='company_email',
        ),
    ]
