# Generated by Django 4.1.5 on 2023-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Company name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
