language: python
python:
  - "3.10"
  - "3.11"
branches:
  only:
    - master
# Start services.
services:
  - redis-server
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install --editable .
  - pip install coveralls
before_script:
  - cp .env.example .env
  - psql -c "CREATE DATABASE snakeeyes;" -U postgres
  - psql -c "CREATE DATABASE snakeeyes_test;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - python manage.py test --settings=config.test_settings
after_success:
  - coveralls
sudo: false


env:
  - DJANGO_VERSION=2.2.9
  - DJANGO_VERSION=3.0.3
branches:
  only:
    - master
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements/local.txt
# command to run tests
script:
  - pytest
