# Generated by Django 4.1.5 on 2023-01-29 05:06

import apps.jobs.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25, unique=True, verbose_name="Name")),
                ("slug", models.SlugField(max_length=25, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("image", models.ImageField(blank=True, upload_to=apps.jobs.utils.image_path, verbose_name="Image")),
                (
                    "category_order",
                    models.PositiveIntegerField(blank=True, unique=True, verbose_name="Category order"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["category_order"],
            },
        ),
        migrations.CreateModel(
            name="JobType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=15, unique=True, verbose_name="Name")),
                ("slug", models.SlugField(max_length=15, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Job Type",
                "verbose_name_plural": "Job Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25, unique=True, verbose_name="Name")),
                ("slug", models.SlugField(max_length=25, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "salary_mode",
                    models.CharField(
                        choices=[("H", "Hourly"), ("D", "Daily"), ("W", "Weekly"), ("M", "Monthly"), ("Y", "Yearly")],
                        max_length=1,
                        verbose_name="Salary Mode",
                    ),
                ),
                ("base_salary_amount", models.PositiveIntegerField()),
                ("maximum_salary_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("experience", models.PositiveIntegerField(blank=True, null=True, verbose_name="Years of experience")),
                ("vacancy", models.PositiveIntegerField(blank=True, null=True)),
                ("application_deadline", models.DateField()),
                (
                    "qualification_title",
                    models.CharField(blank=True, max_length=50, verbose_name="Qualification title"),
                ),
                ("gender", models.CharField(blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1)),
                ("status", models.CharField(choices=[("A", "Active"), ("I", "Inactive")], default="A", max_length=1)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("sponsored", models.BooleanField(default=False, verbose_name="Sponsored")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "applicants",
                    models.ManyToManyField(
                        blank=True, default=None, related_name="applicants", to="accounts.employee"
                    ),
                ),
                ("bookmarks", models.ManyToManyField(blank=True, related_name="bookmarks", to="accounts.employee")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="jobs.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="accounts.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "jobtype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.jobtype",
                        verbose_name="Job Type",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="jobs.state", verbose_name="State"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["application_deadline", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note", models.TextField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("A", "Accepted"), ("R", "Rejected")], default="P", max_length=1
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="accounts.employee",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="jobs.job"
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
