# Generated by Django 4.1.5 on 2023-02-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
