# Generated by Django 5.0.2 on 2024-03-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_testimonial_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testimonial",
        ),
    ]
