# Generated by Django 5.0.2 on 2024-02-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the Help Article.", max_length=255, unique=True, verbose_name="title"
                    ),
                ),
                ("slug", models.SlugField(help_text="URL slug parameter", max_length=255, verbose_name="slug")),
                ("content", models.TextField(help_text="Content of the Article.", verbose_name="content")),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=30, verbose_name="name")),
                ("slug", models.SlugField(max_length=30, verbose_name="slug")),
                ("description", models.CharField(max_length=100, verbose_name="description")),
                ("icon", models.CharField(max_length=20, verbose_name="fontawesome icon")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
