# Generated by Django 5.0.2 on 2024-03-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0002_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                help_text="Category linked to this Help Article.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="help.category",
                verbose_name="category",
            ),
        ),
    ]
