# Generated by Django 5.0.2 on 2024-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0003_alter_article_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255, unique=True, verbose_name="question")),
                ("answer", models.TextField(verbose_name="answer")),
            ],
            options={
                "verbose_name": "frequently asked question",
                "verbose_name_plural": "frequently asked questions",
            },
        ),
    ]
