# Generated by Django 5.0.2 on 2024-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0004_frequentlyaskedquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fullname", models.CharField(max_length=100, verbose_name="full name")),
                ("content", models.CharField(max_length=100, verbose_name="content")),
                ("rating", models.PositiveSmallIntegerField(verbose_name="rating")),
            ],
            options={
                "verbose_name": "testimonial",
                "verbose_name_plural": "testimonials",
            },
        ),
    ]
