# Generated by Django 5.0.2 on 2024-03-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0005_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="fullname",
            field=models.CharField(max_length=30, verbose_name="full name"),
        ),
    ]
